environment:
  matrix:
  - nodejs_version: "Stable"
  - nodejs_version: "6"
  - nodejs_version: "4"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version && npm --version
  - npm run build

build: off

matrix:
  fast_finish: true
